version: '3.7'
services:
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
    networks:
      - spring

  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
      - "7833:7833"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"

    networks:
      - spring

    depends_on:
      - cassandra

  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    networks:
      - spring
    volumes:
      - cassandra-storage:/var/lib/cassandra

networks:
  spring:
    driver: bridge

volumes:
  cassandra-storage:
