server:
  port: 8081
#################################### Cadence Properties ##########################################
cadence:
  domain: test-domain
  host: localhost
  port: 7933
##################################################################################################
